In [2]:
pip install transformers

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.3/6.3 MB 55.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 199.2/199.2 KB 23.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.6/7.6 MB 107.7 MB/s eta 0:00:00


In [3]:
pip install datasets

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 469.0/469.0 KB 10.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 45.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 132.9/132.9 KB 18.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 212.2/212.2 KB 29.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 110.5/110.5 KB 16.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 114.2/114.2 KB 13.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 158.8/158.8 KB 20.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 199.2/199.2 KB 21.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 264.6/264.6 KB 28.1 MB/s eta 0:00:00


In [4]:
from datasets import load_dataset

In [5]:
data=load_dataset('allenai/scitldr')

Generating train split:   0%|          | 0/1992 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/618 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/619 [00:00<?, ? examples/s]

Dataset scitldr downloaded and prepared to /root/.cache/huggingface/datasets/allenai___scitldr/Abstract/0.0.0/79e0fa75961392034484808cfcc8f37deb15ceda153b798c92d9f621d1042fef. Subsequent calls will reuse this data.


  0%|          | 0/3 [00:00<?, ?it/s]

In [6]:
train=data['train']['source']
test=data['test']['source']

In [7]:
type(train)

list

In [8]:
y=''
for i in range(len(train)):
  d=train[i]
  x=''
  for j in range(len(d)):
    x=x+d[j]
  y=y+x
  
y=y.split(" ")

source,target=[],[]
for i in range(len(y)):
  j=i
  if((i+7>=len(y)) or (j+7>=len(y))):
    break
  if(y[i]!=" "):
    source.append(y[i:i+7])
  else:
    i=i+1
    source.append(y[i:i+7])
  if(y[j+7]!=" "):
    target.append(y[j+7])
  else:
    j=j+1
    target.append(y[j+1])

In [9]:
source[0:3]

[['Due', 'to', 'the', 'success', 'of', 'deep', 'learning'],
 ['to', 'the', 'success', 'of', 'deep', 'learning', 'to'],
 ['the', 'success', 'of', 'deep', 'learning', 'to', 'solving']]

In [10]:
len(source)

304322

In [11]:
import pandas as pd

In [12]:
d1=pd.DataFrame()
d1['text']=source[0:30000]
d1['target']=target[0:30000]

In [13]:
d1.head()

text   target
0      [Due, to, the, success, of, deep, learning]       to
1       [to, the, success, of, deep, learning, to]  solving
2  [the, success, of, deep, learning, to, solving]        a
3    [success, of, deep, learning, to, solving, a]  variety
4    [of, deep, learning, to, solving, a, variety]       of

In [14]:
from transformers import GPTNeoForCausalLM,GPT2Tokenizer,DataCollatorForLanguageModeling,Trainer,TrainingArguments

In [15]:
model=GPTNeoForCausalLM.from_pretrained('EleutherAI/gpt-neo-125M')
tokenizer=GPT2Tokenizer.from_pretrained('EleutherAI/gpt-neo-125M')

In [1]:
def tokenize_data(dataframe,column):
  x=[]
  for i in range(len(dataframe.shape[0])):
    x.append(tokenizer(dataframe[column],return_tensors='tf',padding=False))

ss=dict(tokenize_data(d1,'text'))


NameError: ignored

In [ ]:
d1['labels']=dict(tokenize_data(d1,'target'))['input_ids']
d1

In [ ]:
d1['']

In [30]:
tokenizer(d1['text'][0],padding=False,return_tensors='tf')

{'input_ids': <tf.Tensor: shape=(7, 1), dtype=int32, numpy=
array([[22229],
       [ 1462],
       [ 1169],
       [13138],
       [ 1659],
       [22089],
       [40684]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(7, 1), dtype=int32, numpy=
array([[1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1]], dtype=int32)>}